version: '3.6'
services:
  postgres:
    image: postgres:16.2
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:  
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: apple
